discord:
  token: testtoken4
  id: 4
syncplay:
  instances:
    - host: http://localhost:8995
      room: "example
      name: syncbot
      webhooks:
      - url: https://discord.com/api/webhooks/example
        type: DISCORD
