name: Crystal CI
on: push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: Enable Build Cache
      uses: cachix/cachix-action@v9
      with:
        name: zeratax
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Create Test Certs
      run: |
        pushd spec/test_certs
        bash create_certs.sh
        popd

    - name: Build Release
      run: |
        nix-build
        sudo chmod a+x result/bin/dmnd_bot

    - name: Upload release artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: result/bin/dmnd_bot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
